---
- hosts: webservers
  tasks:
    - name: Install EPEL release for nginx
      dnf: 
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm"
        state: present
        disable_gpg_check: yes
      become: yes
    - name: Enable coderead repo
      shell: "dnf config-manager --set-enabled codeready-builder-for-rhel-8-rhui-rpms"
      become: yes
    - name: Install nginx web server
      yum: name=nginx state=installed update_cache=true
      become: yes
      notify:
        - start nginx
    - name: Setup sites
      shell: "mkdir {{ item }}"
      with_items:
        - "/etc/nginx/sites-available/"
        - "/etc/nginx/sites-enabled/"
      become: yes
  handlers:
    - name: start nginx
      service: name=nginx enabled=yes state=started
      become: yes
