---
- hosts: webservers
  tasks:
    - name: Install Latest Java OpenJDK
      yum:
        name: java-latest-openjdk
        state: present
        become: yes
        update_cache: true
    - name: Setting Java Defaults
      alternatives:
        name: java
        link: /usr/bin/java
        path: /usr/lib/jvm/jre-16/bin/java
      environment:
          JAVA_HOME: "/usr/bin/java"
