---
- hosts: webservers
  tasks:
    - name: Install EPEL release for nginx
      yum: name=epel-release state=present
      become: yes
    - name: Install nginx web server
      yum: name=nginx state=installed update_cache=true
      become: yes
      notify:
        - start nginx
    - name: Setup sites
      shell: "mkdir {{ item }}"
      with_items:
        - "/etc/nginx/sites-available/"
        - "/etc/nginx/sites-enabled/"
      become: yes
  handlers:
    - name: start nginx
      service: name=nginx enabled=yes state=started
      become: yes
