
---
- hosts: 159.65.39.230
  tasks:
    - name: Test ping on the host
      ansible.builtin.ping:
      
    - name: just display
      shell: uptime
      register: hostname
      
    - debug:
        var: hostname
