---
- hosts: webservers
  vars: 
    service_name: isitup
    service_username: root
    service_execution_command: "java -jar /opt/isitup/0.0.1-SNAPSHOT.jar"
  tasks:
    - name: Install python-lxml
      dnf:
        name: python3-lxml
        state: present
        disable_gpg_check: yes
      become: yes
#   Download Maven Artifact
    - maven_artifact:
        group_id: com.demoAU
        artifact_id: is-it-up
        extension: jar
        version: 0.0.1-SNAPSHOT
        repository_url: "http://3.19.58.4:8081/repository/isitup-snapshots"
        username: ec2-user
        password: Password
        dest: /opt/isitup/
        keep_name: yes
      become: yes
    - name: Create new service
      template: 
        src: ./templates/rhel/new_service.j2
        dest: /etc/systemd/system/isitup.service
      become: yes
    - name: Execute new service
        ansible.builtin.command: systemctl start isitup  
      become: yes
